name: Docs deploy
on:
  push:
    branches:
      - stable
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'stable'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Check NodeJS environment
        run: |
          node -v
          npm -v
          npx -v

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build:docs

      - name: Deploy docs to Vercel
        run: npx vercel deploy --prod --token ${VERCEL_TOKEN} ./docs
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

